### YamlMime:Architecture
metadata:
  title: Protect access tokens in a single-page application by using Azure API Management 
  description: Implement a No Token in the Browser architecture for a JavaScript single-page application using API Management.
  author: irarainey
  ms.author: irarainey
  ms.date: 07/09/2024
  ms.topic: conceptual
  ms.subservice: architecture-guide
  ms.custom:
    - devx-track-js
    - arb-web
azureCategories:
  - identity
  - security
  - web
products:
  - azure-api-management
  - entra-id
name: Protect access tokens in a single-page application by using Azure API Management 
summary: Implement a No Token in the Browser architecture for a JavaScript single-page application by using API Management.
thumbnailUrl: /azure/architecture/browse/thumbs/no-token.png
content: |
  [!INCLUDE[](secure-single-page-application-authorization-content.md)]
