### YamlMime:Architecture
metadata:
  title: Zero-trust network for web applications with Azure Firewall and Application Gateway
  description: Protect web apps by implementing zero-trust security in virtual networks. Use Azure Firewall and Azure Application Gateway in networks to maximize protection.
  author: erjosito
  ms.author: jomore
  ms.date: 06/07/2024
  ms.topic: conceptual
  ms.service: azure-architecture-center
  ms.subservice: architecture-guide
  ms.category:
    - networking
  ms.custom:
    - fcp
    - guide
    - internal-intro
    - arb-web
name: Zero-trust network for web applications with Azure Firewall and Application Gateway
azureCategories:
  - networking
  - security
summary: Protect web apps by implementing zero-trust security in virtual networks. Use Azure Firewall and Azure Application Gateway in networks to maximize protection.
products:
  - azure-application-gateway
  - azure-firewall
  - azure-virtual-network
  - azure-virtual-wan
  - azure-web-application-firewall
thumbnailUrl: /azure/architecture/browse/thumbs/application-gateway-before-azure-firewall-architecture-thumbnail.png
content: |
   [!include[](application-gateway-before-azure-firewall-content.md)]
