### YamlMime:Architecture
metadata:
  title: Azure Firewall and Application Gateway for Virtual Networks
  description: Learn about options and best practices for how to use Azure Firewall and Azure Application Gateway security in virtual networks.
  author: erjosito
  ms.author: jomore
  ms.date: 01/17/2025
  ms.topic: example-scenario
ms.subservice: example-scenario
  ms.category:
    - networking
    - security
  ms.custom:
    - fcp
    - example-scenario
    - internal-intro
name: Azure Firewall and Application Gateway for virtual networks
azureCategories:
  - networking
  - security
summary: Learn about options and best practices for how to use Azure Firewall and Azure Application Gateway security in virtual networks.
products:
  - azure-application-gateway
  - azure-firewall
  - azure-front-door
  - azure-virtual-network
  - azure-web-application-firewall
thumbnailUrl: /azure/architecture/browse/thumbs/decision-tree.png
content: |
   [!INCLUDE[](firewall-application-gateway-content.md)]
