### YamlMime:Architecture
metadata:
  title: Firewall, App Gateway for virtual networks
  titleSuffix: Azure Example Scenarios
  description: Learn about options and best practices for using Azure Firewall and Azure Application Gateway security in virtual networks.
  author: erjosito
  ms.author: jomore
  ms.date: 08/26/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - networking
    - security
  ms.custom:
    - fcp
    - example-scenario
    - internal-intro
name: Firewall and Application Gateway for virtual networks
azureCategories:
  - networking
  - security
summary: Learn about options and best practices for using Azure Firewall and Azure Application Gateway security in virtual networks.
products:
  - azure-application-gateway
  - azure-firewall
  - azure-front-door
  - azure-virtual-network
  - azure-web-application-firewall
thumbnailUrl: /azure/architecture/browse/thumbs/decision-tree.png
content: |
   [!include[](firewall-application-gateway-content.md)]
