### YamlMime:Architecture
metadata:
  title: Event-based cloud automation
  titleSuffix: Azure Reference Architectures
  description: This article is presents guidance for implementing cloud automation using serverless technologies.
  author: ckittel
  ms.author: chkittel
  ms.date: 9/29/2021
  ms.topic: reference-architecture
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - developer-tools
  ms.custom:
    - reference-architecture
name: Event-based cloud automation
azureCategories:
  - developer-tools
  - devops
summary: This article is presents guidance for implementing cloud automation using serverless technologies.
products:
  - azure-event-grid
  - azure-functions
  - azure-logic-apps
  - azure-monitor
  - azure-cosmos-db
thumbnailUrl: /azure/architecture/browse/thumbs/cloud-automation.png
content: |
   [!include[](cloud-automation-content.md)]
