### YamlMime:Architecture
metadata:
  title: Architectural approaches for the deployment and configuration of multitenant solutions
  description: This article describes approaches to consider when deploying and configuring a multitenant solution.
  author: johndowns
  ms.author: jodowns
  ms.date: 08/01/2024 
  ms.topic: conceptual
  ms.subservice: architecture-guide
  ms.custom:
    - arb-saas
azureCategories:
  - management-and-governance
  - devops
products:
  - azure
  - azure-devops
  - azure-pipelines
  - azure-marketplace
  - github
name: Architectural approaches for the deployment and configuration of multitenant solutions
summary: This article describes approaches to consider when deploying and configuring a multitenant solution.
thumbnailUrl: /azure/architecture/browse/thumbs/example-data-pipeline.png
content: |
  [!include[](deployment-configuration-content.md)]
