### YamlMime:Architecture
metadata:
  title: Azure Arc-enabled server configurations
  description: Use Azure Arc to extend Azure Resource Manager capabilities to Windows and Linux machines on any infrastructure.
  author: pdebruin
  ms.author: pidebrui
  ms.date: 04/29/2022
  ms.topic: reference-architecture
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - hybrid
    - management-and-governance
  ms.custom:
    - fcp
    - reference-architecture
    - e2e-hybrid
    - devx-track-arm-template
name: Manage configurations for Azure Arc-enabled servers
azureCategories:
  - hybrid
  - management-and-governance
summary: Use Azure Arc to extend Azure Resource Manager capabilities to Windows and Linux machines on any infrastructure.
products:
  - azure-arc
  - azure-monitor
  - azure-policy
  - azure-resource-manager
  - azure-virtual-machines
thumbnailUrl: /azure/architecture/browse/thumbs/azure-arc-hybrid-config.png
content: |
   [!include[](azure-arc-hybrid-config-content.md)]
