### YamlMime:Architecture
metadata:
  title: Deploy IBM Maximo Application Suite (MAS) on Azure
  description: Learn how to run IBM Maximo Application Suite (MAS) on Azure. See guidance for designing and implementing cloud solutions with MAS 8.5 and up that use Azure.
  author: ranieuwe
  ms.author: ronieuwe
  ms.date: 11/22/2024
  ms.topic: concept-article
  ms.subservice: architecture-guide
  ms.custom:
    - linux-related-content
azureCategories:
  - compute
  - containers
  - storage
  - analytics
  - iot
products:
  - azure-files
  - azure-load-balancer
  - azure-redhat-openshift
  - azure-virtual-machines
  - azure-virtual-network
name: Deploy IBM Maximo Application Suite on Azure
summary: Learn how to run IBM Maximo Application Suite (MAS) on Azure. See guidance for designing and implementing cloud solutions with Maximo 8.5 and up that use Azure.
thumbnailUrl: /azure/architecture/browse/thumbs/deploy-ibm-maximo-application-suite-thumbnail.png
content: |
  [!INCLUDE[](deploy-ibm-maximo-application-suite-content.md)]
