### YamlMime:Architecture
metadata:
  title: Building blocks for autonomous-driving simulation environments
  titleSuffix: Azure Architecture Center
  description: To assess autonomous driving (AD), function engineers need to simulate the behavior of vehicles with AD capabilities.
  author: martinekuan
  ms.author: gurcan.gulesir
  ms.date: 08/22/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
azureCategories:
  - compute
  - containers
  - devops
products:
  - azure-container-instances
  - azure-active-directory
  - azure-virtual-network
  - azure-virtual-machines
  - azure-pipelines
name: Building blocks for autonomous-driving simulation environments
summary: To assess autonomous driving (AD), function engineers need to simulate the behavior of vehicles with AD capabilities.
thumbnailUrl: /azure/architecture/browse/thumbs/building-blocks-autonomous-driving-simulation-environments.png
content: |
  [!include[](building-blocks-autonomous-driving-simulation-environments-content.md)]
