### YamlMime:Architecture
metadata:
  title: HA enterprise deployment using ASE
  titleSuffix: Azure Reference Architectures
  description: Recommended architecture for deploying an enterprise application using App Services Environment in multiple availability zones.
  author: dsk-2015
  ms.author: dkshir
  ms.date: 05/08/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - management-and-governance
    - featured
  ms.custom:
    - reference-architecture
name: High availability enterprise deployment using App Services Environment
azureCategories:
  - management-and-governance
  - featured
summary: Recommended architecture for deploying an enterprise application using App Services Environment in multiple availability zones.
products:
  - azure-active-directory
  - azure-application-gateway
  - azure-firewall
  - azure-virtual-network
  - azure-app-service
thumbnailUrl: /azure/architecture/browse/thumbs/ha-ase-deployment.png
content: |
   [!include[](ase-high-availability-deployment-content.md)]
