### YamlMime:Architecture
metadata:
  title: Enterprise deployment using Azure ASE
  titleSuffix: Azure Reference Architectures
  description: Learn about the recommended architecture for deploying an enterprise application using App Services Environment in Azure.
  author: dsk-2015
  ms.author: dkshir
  ms.date: 05/08/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - management-and-governance
    - featured
  ms.custom:
    - reference-architecture
name: Enterprise deployment using App Services Environment
azureCategories:
  - management-and-governance
  - featured
summary: Recommended architecture for deploying an enterprise application using App Services Environment.
products:
  - azure-active-directory
  - azure-application-gateway
  - azure-app-service
  - azure-firewall
  - azure-virtual-network
thumbnailUrl: /azure/architecture/browse/thumbs/standard-ase-deployment.png
content: |
   [!include[](ase-standard-deployment-content.md)]
