### YamlMime:Architecture
metadata:
  title: Azure public multi-access edge compute deployment
  titlesuffix: Azure Example Scenarios
  description: Learn how to use Azure public multi-access edge compute to exploit the speed of 5G and unlock key low latency and high bandwidth scenarios.
  author: adhgupta
  ms.author: adhipgupta
  ms.date: 06/13/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom: fcp
azureCategories:
  - hybrid
products:
  - azure-virtual-network
  - azure-kubernetes-service
  - azure-machine-learning
  - ai-services
name: Azure public multi-access edge compute deployment
summary: Learn how to use Azure public multi-access edge compute to exploit the speed of 5G and unlock key low latency and high bandwidth scenarios.
thumbnailUrl: /azure/architecture/browse/thumbs/public-multi-access-edge-compute-deployment.png
content: |
   [!include[](public-multi-access-edge-compute-deployment-content.md)]
