### YamlMime:Architecture
metadata:
  title: Microsoft Entra security for AWS
  description: Learn how Microsoft Entra ID can help secure and protect Amazon Web Services (AWS) identity management and account access. Discover Microsoft security solutions.
  author: claytonsiemens77
  ms.author: pnp
  ms.date: 10/13/2025
  ms.reviewer: joflore
  ms.topic: reference-architecture
  ms.subservice: reference-architecture
  ms.custom:
    - fcp
  keywords:
    - Azure active directory
    - aws identity management
    - identity protection
    - Microsoft security solutions
name: Microsoft Entra identity management and access management for AWS
azureCategories:
  - identity
summary: Learn how Microsoft Entra ID can help secure and protect Amazon Web Services (AWS) identity management and account access. Discover Microsoft security solutions.
products:
  - azure
  - entra-id
thumbnailUrl: /azure/architecture/browse/thumbs/azure-aws-integration.png
content: |
   [!include[](aws-azure-ad-security-content.md)]
