### YamlMime:Architecture
metadata:
  title: Azure AD security for AWS
  titleSuffix: Azure Reference Architectures
  description: Learn how Azure Active Directory can help secure and protect Amazon Web Services (AWS) identity management and account access. Discover Microsoft security solutions.
  author: EdPrice-MSFT
  ms.author: pnp
  ms.date: 12/10/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.custom:
    - fcp
    - seo-aac-fy21q3
  keywords:
    - Azure active directory
    - aws identity management
    - identity protection
    - Microsoft security solutions
name: Azure Active Directory identity management and access management for AWS
azureCategories:
  - identity
summary: Learn how Azure Active Directory can help secure and protect Amazon Web Services (AWS) identity management and account access. Discover Microsoft security solutions.
products:
  - azure
  - azure-active-directory
thumbnailUrl: /azure/architecture/browse/thumbs/azure-aws-integration.png
content: |
   [!include[](aws-azure-ad-security-content.md)]
