### YamlMime:Architecture
metadata:
  title: Deployment Stamps pattern
  description: Learn about the Deployment Stamps pattern, which deploys many independent copies (known as stamps, service units, or scale units) of application components.
  ms.author: robbag
  author: RobBagby
  ms.date: 12/13/2023
  ms.topic: design-pattern
  ms.subservice: design-pattern
azureCategories:
  - management-and-governance
  - security
products:
  - azure-front-door
  - azure
name: Deployment Stamps pattern
summary: Learn about the Deployment Stamps pattern, which deploys many independent copies (known as stamps, service units, or scale units) of application components.
thumbnailUrl: /azure/architecture/browse/thumbs/deployment-stamp-traffic-routing.png
content: |
  [!include[](deployment-stamp-content.md)]
