### YamlMime:Architecture
metadata:
  title: High Availability Enterprise Deployment That Uses App Service Environment
  description: Learn about the recommended architecture to deploy an enterprise application by using App Service Environment in multiple availability zones.
  author: deepbhattacharyya
  ms.author: deepbh
  ms.date: 08/15/2025
  ms.topic: reference-architecture
  ms.subservice: reference-architecture
  ms.category:
    - management-and-governance
    - featured
  ms.custom: arb-web
  ai-usage: ai-assisted
name: High availability enterprise deployment that uses App Service Environment
azureCategories:
  - management-and-governance
  - featured
summary: Learn about the recommended architecture to deploy an enterprise application by using App Service Environment in multiple availability zones.
products:
  - entra-id
  - azure-application-gateway
  - azure-firewall
  - azure-virtual-network
  - azure-app-service
thumbnailUrl: /azure/architecture/browse/thumbs/app-service-environment-high-availability.png
content: |
   [!INCLUDE[](app-service-environment-high-availability-deployment-content.md)]
