### YamlMime:Architecture
metadata:
  title: HA enterprise deployment using ASE
  description: Recommended architecture for deploying an enterprise application using App Services Environment in multiple availability zones.
  author: deepbhattacharyya
  ms.author: deepbh
  ms.date: 08/15/2025
  ms.topic: reference-architecture
  ms.subservice: reference-architecture
  ms.category:
    - management-and-governance
    - featured
  ms.custom: arb-web
name: High availability enterprise deployment using App Service Environment
azureCategories:
  - management-and-governance
  - featured
summary: The recommended architecture for deploying an enterprise application using App Services Environment in multiple availability zones.
products:
  - entra-id
  - azure-application-gateway
  - azure-firewall
  - azure-virtual-network
  - azure-app-service
thumbnailUrl: /azure/architecture/browse/thumbs/app-service-environment-high-availability.png
content: |
   [!INCLUDE[](ase-high-availability-deployment-content.md)]
