### YamlMime:Architecture
metadata:
  title: Automate Sentinel integration with Azure DevOps
  titleSuffix: Azure Example Scenarios
  description: Automate your Microsoft Sentinel integration and deployment with Azure DevOps for your Security Operation Center. 
  author: EdPrice-MSFT
  ms.author: edprice
  ms.date: 2/15/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom: fcp
azureCategories:
  - devops
products:
  - azure-active-directory
  - azure-devops
  - azure-key-vault
  - azure-security-center
  - microsoft-sentinel
name: Automate Sentinel integration with Azure DevOps
summary: Automate your Microsoft Sentinel integration and deployment with Azure DevOps for your Security Operation Center. 
thumbnailUrl: /azure/architecture/browse/thumbs/automate-azure-pipelines-thumbnail.png
content: |
  [!include[](automate-azure-pipelines-content.md)]
