### YamlMime:Architecture
metadata:
  title: Automated API deployments using APIOps
  description: Use APIOps with an Azure API Management instance to build and deploy APIs. This solution provides self-service tools, auditing, policy enforcement, and early feedback.
  author: rishabhsaha
  ms.author: risaha
  ms.date: 07/09/2024
  ms.reviewer: waekdo
  ms.topic: example-scenario
  ms.subservice: example-scenario
  ms.custom:
    - arb-devops
    - arb-web
  ai-usage: ai-assisted
azureCategories:
  - devops
  - developer-tools
  - management-and-governance
products:
  - azure-api-management
  - azure-devops
  - azure-pipelines
name: Automate API deployments with APIOps
summary: Use APIOps with an API Management instance to build and deploy APIs. This solution provides self-service tools, auditing, policy enforcement, and early feedback.
thumbnailUrl: /azure/architecture/browse/thumbs/automated-api-deployments-architecture-diagram-thumb.png
content: |
  [!INCLUDE[](automated-api-deployments-apiops-content.md)]
