### YamlMime:Architecture
metadata:
  title: Real-time machine learning architecture on Azure
  titleSuffix: Azure Architecture Center
  description: Learn how to quickly build an architecture with real-time inference by using Azure Machine Learning and low-code UI with Microsoft Power Platform.
  author: ChristinaSka
  ms.author: christinas
  ms.date: 02/13/2023
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
azureCategories:
  - ai-machine-learning
  - developer-tools
products:
  - azure-machine-learning
  - power-platform
  - power-apps
  - power-automate
  - power-bi
name: Build an architecture with real-time machine learning inference and low-code web application UI on Azure
summary: Learn how to quickly build an architecture with real-time inference by using Azure Machine Learning and low-code UI with Microsoft Power Platform.
thumbnailUrl: /azure/architecture/browse/thumbs/deploy-real-time-machine-learning-model-application-ui.png
content: |
  [!include[](deploy-real-time-machine-learning-model-application-ui-content.md)]
