### YamlMime:Architecture
metadata:
  title: Deploy machine learning models to multiple lines 
  titleSuffix: Azure Example Scenarios
  description: Use a multiline-model architecture to deploy machine learning models to multiple data sources. 
  author: martinekuan
  ms.author: paulbutler 
  ms.date: 05/25/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom: fcp 
azureCategories:
  - "ai-machine-learning"
  - "devops"
products:
  - "azure-machine-learning"
  - "azure-pipelines"
  - "azure-blob-storage"
  - "azure-container-registry"
name: Deploy machine learning models to multiple data sources 
summary: Use a multiline-model architecture to deploy machine learning models to multiple data sources. 
thumbnailUrl: /azure/architecture/browse/thumbs/multiline-deployment-pipeline.png
content: |
  [!include[](multiline-model-deployment-content.md)]
