### YamlMime:Architecture
metadata:
  title: Deploy machine learning models to multiple lines 
  titleSuffix: Azure Example Scenarios
  description: This article describes an architecture that you can use to deploy machine learning models to multiple data sources. 
  author: EdPrice-MSFT
  ms.author: paulbutler 
  ms.date: 01/04/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom: fcp 
azureCategories:
  - "ai-machine-learning"
  - "iot"
products:
  - "azure-machine-learning"
  - "azure-pipelines"
  - "azure-blob-storage"
  - "azure-container-registry"
name: Deploy machine learning models to multiple data sources 
summary: This article describes an architecture that you can use to deploy machine learning models to multiple data sources. 
thumbnailUrl: /azure/architecture/browse/thumbs/multiline-deployment-pipeline.png
content: |
  [!include[](multiline-model-deployment-content.md)]
