### YamlMime:Architecture
metadata:
  title: Blue-green deployment of AKS clusters
  description: Learn how to deploy AKS clusters using a blue-green strategy.
  author: vimorra
  ms.author: vimorra
  ms.date: 05/31/2024
  ms.topic: concept-article
  ms.subservice: architecture-guide
  ms.custom:
  - arb-containers
  ai-usage: ai-assisted
azureCategories:
  - containers
  - devops
  - management-and-governance
products:
  - azure-kubernetes-service
  - azure-application-gateway
  - azure-container-registry
  - azure-front-door
  - azure-dns
name: Blue-green deployment of AKS clusters
summary: Learn how to deploy AKS clusters using a blue-green strategy.
thumbnailUrl: /azure/architecture/browse/thumbs/blue-green-aks-deployment-diagram-public-architecture-thumb.png
content: |
   [!include[](blue-green-deployment-for-aks-content.md)]
