### YamlMime:Architecture
metadata:
  title: Azure Automation State Configuration
  description: Use Azure Automation State Configuration to configure Windows and Linux systems.
  author: EdPrice-MSFT
  ms.author: pnp
  ms.date: 4/22/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - devops
  ms.custom:
    - example-scenario
name: Azure Automation State Configuration
azureCategories:
  - devops
summary: Use Azure Automation State Configuration to configure Windows and Linux systems.
products:
  - azure-automation
  - azure-monitor
  - azure-virtual-machines
thumbnailUrl: /azure/architecture/browse/thumbs/state-config.png
content: |
   [!include[](state-configuration-content.md)]
