### YamlMime:Architecture
metadata:
  title: Add a mobile front end to a legacy app
  titleSuffix: Azure Solution Ideas
  description: This solution consolidates data from multiple business systems and then surfaces the data through web and mobile front ends. This consolidation helps improve employee productivity and helps speed up decision making.
  author: martinekuan
  ms.author: architectures
  ms.date: 07/14/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - migration
    - mobile
  ms.custom:
    - acom-architecture
    - line of business app
    - lob app
    - lift and shift cloud strategy
    - cloud migration
    - cloud innovation
    - lift and shift solution
    - lift and shift strategy
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/adding-a-modern-web-and-mobile-frontend-to-a-legacy-claims-processing-application"
name: Add a mobile front end to a legacy app
azureCategories:
  - migration
  - mobile
summary: This solution consolidates data from multiple business systems and then surfaces the data through web and mobile front ends. This consolidation helps improve employee productivity and helps speed up decision making.
products:
  - azure-active-directory
  - azure-active-directory-b2c
  - azure-sql-database
  - azure-virtual-machines
thumbnailUrl: /azure/architecture/browse/thumbs/adding-a-modern-web-and-mobile-frontend-to-a-legacy-claims-processing-application.png
content: |
   [!include[](adding-a-modern-web-and-mobile-frontend-to-a-legacy-claims-processing-application-content.md)]
