### YamlMime:Architecture
metadata:
  title: Centralized app configuration and security
  titleSuffix: Azure Solution Ideas
  description: Use Azure App Configuration and Azure Key Vault to create a centralized and secured configuration service for apps.
  author: sowmyans
  ms.author: sowmyans
  ms.date: 05/13/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - security
    - management-and-governance
  ms.custom:
    - fcp
name: Centralized app configuration and security
azureCategories:
  - security
  - management-and-governance
summary: Use Azure App Configuration and Azure Key Vault to create a centralized and secured configuration service for apps.
products:
  - azure-active-directory
  - azure-app-configuration
  - azure-key-vault
thumbnailUrl: /azure/architecture/browse/thumbs/appconfig-development.png
content: |
   [!include[](appconfig-key-vault-content.md)]
