### YamlMime:Architecture
metadata:
  title: Application integration using Azure Event Grid
  titleSuffix: Azure Architecture Center
  description: Learn how to integrate your app with Azure Event Grid and take advantage of its reliable delivery, advanced routing, and direct integration.
  author: martinekuan
  ms.author: architectures
  ms.date: 07/14/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - analytics
  ms.custom:
    - acom-architecture
    - application-development
    - event-grid
    - azure
    - "https://azure.microsoft.com/solutions/architecture/application-integration-using-event-grid"
name: Application integration using Azure Event Grid
azureCategories:
  - analytics
summary: This scenario shows you how to create an application topic to send your app event data to Azure Event Grid. Take advantage of its reliable delivery, advanced routing, and direct integration.
products:
  - azure-event-grid
  - azure-functions
  - azure-logic-apps
thumbnailUrl: /azure/architecture/browse/thumbs/application-integration-using-event-grid.png
content: |
   [!include[](application-integration-using-event-grid-content.md)]
