### YamlMime:Architecture
metadata:
  title: Blockchain workflow application
  titleSuffix: Azure Architecture Center
  description: Explore how blockchain is used to digitize workflows and supply chains across organizations with the Blockchain Workflow Application from Microsoft Azure.
  author: EdPrice-MSFT
  ms.author: architectures
  ms.date: 07/14/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - blockchain
    - compute
  ms.custom:
    - acom-architecture
    - blockchain
    - Blockchain Workflow Application
    - Azure Blockchain
    - Azure Blockchain Service
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/blockchain-workflow-application"
  social_image_url: /azure/architecture/solution-ideas/articles/media/blockchain-workflow-application.png
name: Blockchain workflow application
azureCategories:
  - compute
summary: Explore how blockchain is used to digitize workflows and supply chains across organizations with the Blockchain Workflow Application from Microsoft Azure.
products:
  - azure-blockchain-service
  - azure-service-bus
  - azure-iot-central
  - azure-event-grid
thumbnailUrl: /azure/architecture/browse/thumbs/blockchain-workflow-application.png
content: |
   [!include[](blockchain-workflow-application-content.md)]
