### YamlMime:Architecture
metadata:
  title: DevOps in a hybrid environment
  titleSuffix: Azure Solution Ideas
  description: The tools provided in Azure allow for the implementation of a DevOps strategy that capably manages both cloud and on-premises environments in tandem.
  author: EdPrice-MSFT
  ms.author: asegala
  ms.date: 12/16/2019
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - devops
    - hybrid
  ms.custom:
    - acom-architecture
    - e2e-hybrid
  social_image_url: /azure/architecture/solution-ideas/articles/media/devops-in-a-hybrid-environment.png
name: DevOps in a hybrid environment
azureCategories:
  - devops
  - hybrid
summary: The tools provided in Azure allow for the implementation of a DevOps strategy that capably manages both cloud and on-premises environments in tandem.
products:
  - azure-active-directory
  - azure-key-vault
  - azure-boards
  - azure-monitor
  - azure-pipelines
thumbnailUrl: /azure/architecture/browse/thumbs/devops-in-a-hybrid-environment.png
content: |
   [!include[](devops-in-a-hybrid-environment-content.md)]
