### YamlMime:Architecture
metadata:
  title: Environment monitoring and supply chain optimization with IoT
  titleSuffix: Azure Solution Ideas
  description: Learn how to use Azure IoT for environment monitoring and supply chain optimization.
  author: falloutxAY
  ms.author: ansyeo
  ms.date: 07/09/2024
  ms.topic: solution-idea
  ms.service: azure-architecture-center
  ms.subservice: solution-idea
  ms.category:
    - iot
  ms.custom: arb-iot
name: Environment monitoring and supply chain optimization with IoT
azureCategories:
  - iot
summary: Learn how to use Azure IoT for environment monitoring and supply chain optimization.
products:
  - azure-functions
  - azure-iot
  - azure-storage
  - azure-machine-learning
  - azure-databricks
  - azure-monitor
thumbnailUrl: /azure/architecture/browse/thumbs/environment-monitor-supply-chain-thumbnail.png
content: |
   [!include[](environment-monitoring-and-supply-chain-optimization-content.md)]
