### YamlMime:Architecture
metadata:
  title: Globally distributed applications using Azure Cosmos DB
  titleSuffix: Azure Example Scenarios
  description: Guarantee access to users around the world with the high-availability and low-latency capabilities built into Microsoft global datacenters.
  author: martinekuan
  ms.author: architectures
  ms.date: 05/27/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - databases
    - management-and-governance
  ms.custom:
    - acom-architecture
    - app-dev
    - Cosmos DB
    - "https://azure.microsoft.com/solutions/architecture/globally-distributed-mission-critical-applications-using-cosmos-db"
name: Globally distributed applications using Azure Cosmos DB
azureCategories:
  - databases
  - management-and-governance
summary: Guarantee access to users around the world with the high-availability and low-latency capabilities built into Microsoft global datacenters.
products:
  - azure-cosmos-db
  - azure-traffic-manager
thumbnailUrl: /azure/architecture/browse/thumbs/globally-distributed-mission-critical-applications-using-cosmos-db.png
content: |
   [!include[](globally-distributed-mission-critical-applications-using-cosmos-db-content.md)]
