### YamlMime:Architecture
metadata:
  title: Globally distributed applications using Cosmos DB
  titleSuffix: Azure Example Scenarios
  description: Guarantee access to users around the world with the high-availability and low-latency capabilities built into Microsoft global datacenters.
  author: t2kx
  ms.author: mimar
  ms.date: 02/09/2021
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - databases
    - management-and-governance
  ms.custom:
    - acom-architecture
    - app-dev
    - Cosmos DB
    - "https://azure.microsoft.com/solutions/architecture/globally-distributed-mission-critical-applications-using-cosmos-db/"
  social_image_url: /azure/architecture/solution-ideas/articles/media/globally-distributed-mission-critical-applications-using-cosmos-db.png
name: Globally distributed applications using Cosmos DB
azureCategories:
  - databases
  - management-and-governance
summary: Guarantee access to users around the world with the high-availability and low-latency capabilities built into Microsoft global datacenters.
products:
  - azure-cosmos-db
  - azure-traffic-manager
thumbnailUrl: /azure/architecture/browse/thumbs/globally-distributed-mission-critical-applications-using-cosmos-db.png
content: |
   [!include[](globally-distributed-mission-critical-applications-using-cosmos-db-content.md)]
