### YamlMime:Architecture
metadata:
  title: Deploy machine learning models to AKS with Kubeflow
  titleSuffix: Azure Solution Ideas
  description: Deploy machine learning models to Azure Kubernetes Service (AKS) for high-scale production inference.
  author: EdPrice-MSFT
  ms.author: pnp
  ms.date: 12/16/2019
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - ai-machine-learning
    - containers
  ms.custom:
    - acom-architecture
    - chat
    - signalr service
    - interactive-diagram
    - devops
    - microservices
    - ai-ml
    - "https://azure.microsoft.com/solutions/architecture/machine-learning-model-deployment-aks/"
    - ai-machine-learning
    - aml-project-improvement
  social_image_url: /azure/architecture/solution-ideas/articles/media/machine-learning-model-deployment-to-aks.png
name: Deploy machine learning models to AKS with Kubeflow
azureCategories:
  - ai-machine-learning
  - containers
summary: Deploy machine learning models on Azure Kubernetes Service (AKS) for high-scale production inference.
products:
  - azure-blob-storage
  - azure-container-registry
  - azure-kubernetes-service
thumbnailUrl: /azure/architecture/browse/thumbs/machine-learning-model-deployment-to-aks.png
content: |
  [!include[](machine-learning-model-deployment-aks-content.md)]
