### YamlMime:Architecture
metadata:
  title: Map threats to your IT environment
  titleSuffix: Azure Architecture Center
  description: Diagram the IT environment of your organization and develop a threat map to plan and build your defensive layer of security. This article is part of a series.
  author: rudneir2
  ms.author: ruolivei
  ms.custom: fcp
  ms.date: 10/10/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
azureCategories:
  - integration
  - security
products:
  - azure
  - office-365
name: Map threats to your IT environment
summary: Diagram the IT environment of your organization and develop a threat map to plan and build your defensive layer of security. This article is part of a series.
thumbnailUrl: /azure/architecture/browse/thumbs/map-threats-it-environment-thumbnail.png
content: |
  [!include[](map-threats-it-environment-content.md)]
