### YamlMime:Architecture
metadata:
  title: Lift and shift to containers with Azure App Service
  titleSuffix: Azure Architecture Center
  description: Migrate existing web apps to containers deployed in App Service, which allows you to focus on composing containers not worrying about managing container orchestration.
  author: vmagelo 
  ms.author: v-gelorminom
  ms.date: 12/29/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - migration
    - containers
    - web
  ms.custom:
    - acom-architecture
    - app-dev
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/migrate-existing-applications-to-container-apps"
  social_image_url: /azure/architecture/solution-ideas/articles/media/migrate-existing-applications-to-container-apps.png
name: Lift and shift to containers with Azure App Service
azureCategories:
  - migration
  - containers
summary: Migrate existing web apps to containers deployed in App Service, which allows you to focus on composing containers not worrying about managing container orchestration.
products:
  - azure-active-directory
  - azure-container-registry
  - azure-app-service
thumbnailUrl: /azure/architecture/browse/thumbs/migrate-existing-applications-to-container-apps.png
content: |
   [!include[](migrate-existing-applications-to-container-apps-content.md)]
