### YamlMime:Architecture
metadata:
  title: Lift and shift to containers with AKS
  titleSuffix: Azure Solution Ideas
  description: Migrate existing applications to containers in Azure Kubernetes Service (AKS). Use Open Service Broker for Azure (OSBA) to access Azure databases.
  author: EdPrice-MSFT
  ms.author: pnp
  ms.date: 12/18/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - migration
    - containers
  ms.custom:
    - acom-architecture
    - app-dev
    - devops
    - chat
    - signalr service
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/migrate-existing-applications-with-aks/"
  social_image_url: /azure/architecture/solution-ideas/articles/media/migrate-existing-applications-with-aks.png
name: Lift and shift to containers with AKS
azureCategories:
  - migration
  - containers
summary: Migrate existing applications to containers in Azure Kubernetes Service (AKS). Use Open Service Broker for Azure (OSBA) to access Azure databases.
products:
  - azure-active-directory
  - azure-container-registry
  - azure-database-mysql
  - azure-kubernetes-service
thumbnailUrl: /azure/architecture/browse/thumbs/migrate-existing-applications-with-aks.png
content: |
   [!include[](migrate-existing-applications-with-aks-content.md)]
