### YamlMime:Architecture
metadata:
  title: Scalable web and mobile applications using Azure Database for PostgreSQL
  titleSuffix: Azure Solution Ideas
  description: Use Azure Database for PostgreSQL to rapidly build engaging, performant, and scalable cross-platform and native apps for iOS, Android, Windows, or Mac.
  author: doodlemania2
  ms.author: pnp
  ms.date: 12/16/2019
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - mobile
    - web
    - databases
  ms.custom:
    - acom-architecture
    - postgresql
    - web-app
    - scalability
    - use cases
    - azure
    - solutions
    - 'https://azure.microsoft.com/solutions/architecture/scalable-web-and-mobile-applications-using-azure-database-for-postgresql/'
  social_image_url: /azure/architecture/solution-ideas/articles/media/scalable-web-and-mobile-applications-using-azure-database-for-postgresql.png
name: Scalable web and mobile applications using Azure Database for PostgreSQL
azureCategories:
  - mobile
  - web
  - databases
summary: Use Azure Database for PostgreSQL to rapidly build engaging, performant, and scalable cross-platform and native apps for iOS, Android, Windows, or Mac.
products:
  - azure-app-service
  - azure-database-postgresql
  - azure-traffic-manager
thumbnailUrl: /azure/architecture/browse/thumbs/scalable-web-and-mobile-applications-using-azure-database-for-postgresql.png
content: |
   [!include[](scalable-web-and-mobile-applications-using-azure-database-for-postgresql-content.md)]
