### YamlMime:Architecture
metadata:
  title: Scalable apps using Azure DB for MySQL
  titleSuffix: Azure Solution Ideas
  description: Use Azure Database for MySQL to rapidly build engaging, performant, and scalable cross-platform and native apps for iOS, Android, Windows, or Mac.
  author: mootpointer
  ms.author: anharvey
  ms.date: 11/25/2021
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - mobile
    - web
    - databases
  ms.custom:
    - acom-architecture
    - mysql
    - web-app
    - scalability
    - use cases
    - azure
    - solutions
    - "https://azure.microsoft.com/solutions/architecture/scalable-web-and-mobile-applications-using-azure-database-for-mysql/"
  social_image_url: /azure/architecture/solution-ideas/articles/media/scalable-web-and-mobile-applications-using-azure-database-for-mysql.png
name: Scalable web and mobile applications using Azure Database for MySQL
azureCategories:
  - mobile
  - web
  - databases
summary: Use Azure Database for MySQL to rapidly build engaging, performant, and scalable cross-platform and native apps for iOS, Android, Windows, or Mac.
products:
  - azure-app-service
  - azure-database-mysql
thumbnailUrl: /azure/architecture/browse/thumbs/scalable-web-and-mobile-applications-using-azure-database-for-mysql.png
content: |
   [!include[](scalable-web-and-mobile-applications-using-azure-database-for-mysql-content.md)]
