### YamlMime:Architecture
metadata:
  title: Serverless application architectures using Event Grid
  titleSuffix: Azure Solution Ideas
  description: Use Event Grid to connect data sources and event handlers. Trigger a serverless function to run image analysis when a new photo enters a blob storage container.
  author: Herman-Wu
  ms.author: hermanwu
  ms.date: 06/13/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - developer-tools
  ms.custom:
    - acom-architecture
    - serverless
    - event-grid
    - azure
    - "https://azure.microsoft.com/solutions/architecture/serverless-application-architectures-using-event-grid"
name: Serverless application architectures using Event Grid
azureCategories:
  - developer-tools
summary: Use Event Grid to connect data sources and event handlers. Trigger a serverless function to run image analysis when a new photo enters a blob storage container.
products:
  - azure-event-grid
  - azure-blob-storage
thumbnailUrl: /azure/architecture/browse/thumbs/serverless-application-architectures-using-event-grid.png
content: |
   [!include[](serverless-application-architectures-using-event-grid-content.md)]
