### YamlMime:Architecture
metadata:
  title: Create a Gridwich cloud environment
  titleSuffix: Azure Reference Architectures
  description: Learn how to create cloud environments in Azure DevOps. Use the ci_cd_ext_release or tf_destroy_env pipelines to create or delete cloud development or testing environments.
  author: martinekuan
  ms.author: architectures
  ms.date: 07/28/2022
  ms.topic: reference-architecture
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.custom:
    - fcp
    - seo-aac-fy21q3
  keywords:
    - gridwich environment
    - create environment
    - azure devops projects
    - cloud environment
name: How to create a Gridwich environment
summary: Learn how to create cloud environments in Azure DevOps. Use the ci_cd_ext_release or tf_destroy_env pipelines to create or delete cloud development or testing environments.
products:
  - azure-devops
  - azure-storage-accounts
thumbnailUrl: /azure/architecture/browse/thumbs/request-response.png
content: |
   [!include[](create-delete-cloud-environment-content.md)]
