### YamlMime:Architecture
metadata:
  title: Gridwich local development environment setup
  titleSuffix: Azure Reference Architectures
  description: Set up a local development environment to work with Gridwich.
  author: EdPrice-MSFT
  ms.author: pnp
  ms.date: 11/12/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.custom:
    - fcp
name: Gridwich local development environment setup
summary: Set up a local development environment to work with Gridwich.
products:
  - azure-devops
  - azure-key-vault
thumbnailUrl: /azure/architecture/browse/thumbs/request-response.png
content: |
   [!include[](set-up-local-environment-content.md)]
