### YamlMime:Architecture
metadata:
  title: Use deployment scripts to check resource properties
  description: Use Bicep and a deployment script to pause a deployment in order to wait for a resource property to return a specific value.
  author: jtracey93
  ms.author: jatracey
  ms.date: 09/13/2024
  ms.topic: concept-article
  ms.subservice: architecture-guide
  ms.custom:
    - devx-track-bicep
    - arb-devops
azureCategories:
  - devops
  - networking
products:
  - azure-resource-manager
  - azure-virtual-network
  - azure-virtual-wan
name: Use deployment scripts to check resource properties
summary: Use Bicep and a deployment script to pause a deployment in order to wait for a resource property to return a specific value.
thumbnailUrl: /azure/architecture/browse/thumbs/deployment-scripts-property-check.png
content: |
  [!include[](deployment-scripts-property-check-content.md)]
