### YamlMime:Architecture
metadata:
  title: Refactor mainframe applications with Astadia
  titleSuffix: Azure Architecture Center
  description: See an architecture that uses Astadia to migrate COBOL applications from an on-premises environment to the cloud.
  author: martinekuan
  ms.author: ricronhe
  ms.date: 07/01/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom:
    - fcp
azureCategories:
  - migration
  - developer-tools
products:
  - azure-expressroute
  - azure-bastion
  - azure-load-balancer
  - azure-private-link
  - azure-site-recovery
name: Refactor mainframe applications with Astadia
summary: See an architecture that uses Astadia to migrate COBOL applications from an on-premises environment to the cloud.
thumbnailUrl: /azure/architecture/browse/thumbs/refactor-mainframe-applications-astadia-post.png
content: |
   [!include[](refactor-mainframe-applications-astadia-content.md)]
