### YamlMime:Architecture
metadata:
  title: Refactor mainframe applications with Advanced
  titleSuffix: Azure Architecture Center
  description: Learn how to use the Automated COBOL Refactoring solution from Advanced to modernize your mainframe COBOL applications, run them on Azure, and reduce costs.
  author: bhbandam
  ms.author: bhbandam
  ms.date: 07/01/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - migration
  ms.custom:
    - fcp
azureCategories:
  - migration
products:
  - azure-files
  - azure-load-balancer
  - azure-sql-database
  - azure-storage
  - azure-virtual-machines
name: Refactor mainframe applications with Advanced
summary: Learn how to use the Automated COBOL Refactoring solution from Advanced to modernize your mainframe COBOL applications, run them on Azure, and reduce costs.
thumbnailUrl: /azure/architecture/browse/thumbs/refactor-mainframe-applications-advanced-post.png
content: |
   [!include[](refactor-mainframe-applications-advanced-content.md)]
