### YamlMime:Architecture
metadata:
  title: Deployment Patterns for Microsoft Fabric
  titleSuffix: Azure Architecture Center
  description: Learn about common deployment scenarios for Microsoft Fabric.
  ms.author: csiemens
  author: claytonsiemens77
  ms.date: 03/28/2025
  ms.topic: conceptual
    ms.subservice: architecture-guide
  ms.category:
    - analytics
  ms.custom: arb-data
name: Microsoft Fabric deployment patterns
azureCategories:
  - analytics
summary: This article provides an overview of common deployment scenarios for Microsoft Fabric.
products:
  - fabric
thumbnailUrl: /azure/architecture/browse/thumbs/fabric-deployment-pattern-1-monolithic-deployment.png
content: |
   [!INCLUDE[](fabric-deployment-patterns-content.md)]
