### YamlMime:Architecture
metadata:
  title: Blue-green deployment for AKS
  titleSuffix: Azure Architecture Center
  description: Learn how to implement a blue-green deployment system on AKS that uses Azure managed services and native Kubernetes features. 
  author: vimorra
  ms.author: vimorra
  ms.date: 02/01/2023
  ms.topic: conceptual
  ms.service: architecture-center
azureCategories:
  - containers
  - devops
  - management-and-governance
products:
  - azure-kubernetes-service
  - azure-application-gateway
  - azure-container-registry
  - azure-front-door
  - azure-dns
name: Blue-green deployment for AKS
summary: Learn how to implement a blue-green deployment system on AKS that uses Azure managed services and native Kubernetes features. 
thumbnailUrl: /azure/architecture/browse/thumbs/blue-green-aks-deployment-diagram-public-architecture-thumb.png
content: |
   [!include[](blue-green-deployment-for-aks-content.md)]
