name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 */24 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Stale configuration
        days-before-pr-stale: 14
        stale-pr-label: inactive
        stale-pr-message: >
          This pull request has been inactive for 14 days.
          If you are finished with your changes, don't forget to sign off. See the [contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-automation) for instructions.
          
          Other resources:
          
          - [Get Help](https://review.docs.microsoft.com/help/contribute/help-options?branch=master)
          
          - [Docs Support Teams Channel](https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
          
          - [Resolve Merge Conflict](https://review.docs.microsoft.com/help/contribute/resolve-merge-conflicts?branch=master)
          

        
        # Auto-close configuration
        days-before-pr-close: 9999
        close-pr-label: auto-close
        exempt-pr-labels: keep-open
        close-pr-message: > 
          This pull request (PR) has been inactive for a long time. At this time, we are closing the PR.  
          If you want to continue working on your change, reopen the PR. Thank you! 


