### YamlMime:Architecture
metadata:
  title: Scale IoT solutions with deployment stamps
  titleSuffix: Azure Example Scenarios
  description: Learn about scaling up IoT device populations with deployment stamps and strategies for moving devices and applications between stamps.
  author: wamachine
  ms.date: 04/22/2021
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - iot
  ms.custom:
    - fcp
    - example-scenario
name: Scale IoT solutions with deployment stamps
azureCategories:
  - iot
summary: Learn about scaling up IoT device populations with deployment stamps and strategies for moving devices and applications between stamps.
products:
  - azure-event-hubs
  - azure-iot-hub
  - azure-traffic-manager
  - azure-iot-dps
thumbnailUrl: /azure/architecture/browse/thumbs/scale-iot-deployment-stamps.svg
content: |
   [!include[](application-stamps-content.md)]
