### YamlMime:Architecture
metadata:
  title: Scale and manage IoT solutions with deployment stamps
  titleSuffix: Azure Example Scenarios
  description: Learn about scaling up and managing IoT device populations with deployment stamps, and see how to move devices and applications between stamps.
  author: wamachine
  ms.author: jasonwa
  ms.date: 09/22/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - iot
  ms.custom:
    - fcp
    - example-scenario
name: Scale and manage IoT solutions with deployment stamps
azureCategories:
  - iot
summary: Learn about scaling up and managing IoT device populations with deployment stamps, and see how to move devices and applications between stamps.
products:
  - azure-event-hubs
  - azure-iot-dps
  - azure-iot-hub
  - azure-traffic-manager
thumbnailUrl: /azure/architecture/browse/thumbs/scale-iot-deployment-stamps-thumbnail.png
content: |
   [!include[](application-stamps-content.md)]
