### YamlMime:Architecture
metadata:
  title: Efficient Docker image deployment for low-bandwidth connectivity
  titleSuffix: Azure Example Workloads
  description: See an example solution for reliable and resilient Docker image deployment over limited, intermittent, or low bandwidth.
  author: martinekuan
  ms.author: kadimitr
  ms.date: 03/21/2023
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
name: Efficient Docker image deployment for low-bandwidth connectivity
azureCategories:
  - devops
  - iot
summary: See an example solution for reliable and resilient Docker image deployment over limited, intermittent, or low bandwidth.
products:
  - azure-container-registry
  - azure-functions
  - azure-iot-edge
  - azure-iot-hub
  - azure-pipelines

thumbnailUrl: /azure/architecture/browse/thumbs/efficient-docker-image-deployment-01.png
content: |
   [!include[](efficient-docker-image-deployment-content.md)]
